import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { fid, username, displayName, score, tier, stats, avatarUrl } = await req.json();
    
    console.log(`Generating NFT metadata for user: ${username}, score: ${score}, tier: ${tier}`);

    // Generate NFT metadata following OpenSea standards
    const metadata = {
      name: `Niner Score #${fid}`,
      description: `Farcaster Identity Card for @${username}. This NFT represents their social reputation score of ${score} points, achieving ${tier.toUpperCase()} tier status. Generated by Niner Score - the gamified reputation system for Farcaster.`,
      image: avatarUrl || `https://api.dicebear.com/7.x/shapes/svg?seed=${username}`,
      external_url: `https://warpcast.com/${username}`,
      background_color: tier === 'diamond' ? '00BFFF' : tier === 'gold' ? 'FFD700' : tier === 'silver' ? 'C0C0C0' : 'CD7F32',
      attributes: [
        {
          trait_type: "Niner Score",
          value: score,
          display_type: "number"
        },
        {
          trait_type: "Tier",
          value: tier.charAt(0).toUpperCase() + tier.slice(1)
        },
        {
          trait_type: "Farcaster ID",
          value: fid,
          display_type: "number"
        },
        {
          trait_type: "Username",
          value: username
        },
        {
          trait_type: "Total Casts",
          value: stats?.casts || 0,
          display_type: "number"
        },
        {
          trait_type: "Followers",
          value: stats?.followers || 0,
          display_type: "number"
        },
        {
          trait_type: "Engagement Rate",
          value: stats?.engagement || 0,
          display_type: "number"
        },
        {
          trait_type: "Generation Date",
          value: new Date().toISOString().split('T')[0]
        }
      ],
      properties: {
        category: "social",
        creators: [
          {
            address: "niner-score",
            share: 100
          }
        ]
      }
    };

    // Generate a unique token ID based on FID and timestamp
    const tokenId = `${fid}-${Date.now()}`;
    
    // OpenSea testnet URL (for demo purposes)
    // In production, you'd mint to a real contract and get the actual OpenSea URL
    const openSeaUrl = `https://testnets.opensea.io/assets/base-sepolia/0x0000000000000000000000000000000000000000/${tokenId}`;
    
    console.log('Generated metadata:', JSON.stringify(metadata));

    return new Response(JSON.stringify({ 
      metadata,
      tokenId,
      openSeaUrl,
      // For demo, we return a mock OpenSea-like URL
      previewUrl: `https://opensea.io/collection/niner-score?search[query]=${username}`,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error generating NFT metadata:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
