import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { fid } = await req.json();
    
    // Validate FID format
    if (!fid || !Number.isInteger(fid) || fid <= 0) {
      return new Response(
        JSON.stringify({ error: 'Invalid FID format' }),
        { 
          status: 400, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      );
    }

    console.log(`Generating NFT metadata for FID: ${fid}`);

    // Fetch verified data from leaderboard (already validated by save-to-leaderboard)
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const { data: userData, error: dbError } = await supabase
      .from('leaderboard')
      .select('*')
      .eq('fid', fid)
      .single();

    if (dbError || !userData) {
      console.error('User not found in leaderboard:', dbError);
      return new Response(
        JSON.stringify({ error: 'User not found in leaderboard. Please save your score first.' }),
        { 
          status: 404, 
          headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
        }
      );
    }

    const { username, display_name, avatar_url, score, tier, casts, followers, engagement } = userData;

    // Generate NFT metadata following OpenSea standards using SERVER-VALIDATED data only
    const metadata = {
      name: `Niner Score #${fid}`,
      description: `Farcaster Identity Card for @${username}. This NFT represents their social reputation score of ${score} points, achieving ${tier.toUpperCase()} tier status. Generated by Niner Score - the gamified reputation system for Farcaster.`,
      image: avatar_url || `https://api.dicebear.com/7.x/shapes/svg?seed=${username}`,
      external_url: `https://warpcast.com/${username}`,
      background_color: tier === 'diamond' ? '00BFFF' : tier === 'gold' ? 'FFD700' : tier === 'silver' ? 'C0C0C0' : 'CD7F32',
      attributes: [
        {
          trait_type: "Niner Score",
          value: score,
          display_type: "number"
        },
        {
          trait_type: "Tier",
          value: tier.charAt(0).toUpperCase() + tier.slice(1)
        },
        {
          trait_type: "Farcaster ID",
          value: fid,
          display_type: "number"
        },
        {
          trait_type: "Username",
          value: username
        },
        {
          trait_type: "Total Casts",
          value: casts || 0,
          display_type: "number"
        },
        {
          trait_type: "Followers",
          value: followers || 0,
          display_type: "number"
        },
        {
          trait_type: "Engagement Rate",
          value: engagement || 0,
          display_type: "number"
        },
        {
          trait_type: "Generation Date",
          value: new Date().toISOString().split('T')[0]
        }
      ],
      properties: {
        category: "social",
        creators: [
          {
            address: "niner-score",
            share: 100
          }
        ]
      }
    };

    // Generate a unique token ID based on FID and timestamp
    const tokenId = `${fid}-${Date.now()}`;
    
    console.log('Generated metadata for user:', username, 'score:', score, 'tier:', tier);

    return new Response(JSON.stringify({ 
      metadata,
      tokenId,
      previewUrl: `https://opensea.io/collection/niner-score?search[query]=${username}`,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error generating NFT metadata:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
